### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Furnicarium** [cbnuke/Bagaroung_shop#1]
it doesn't work.
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257

Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at D:\OpenServer\domains\bagaround.ru\system\core\Exceptions.php:185)
Filename: libraries/Session.php
Line Number: 675

Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at D:\OpenServer\domains\bagaround.ru\system\core\Exceptions.php:185)
Filename: core/Common.php
Line Number: 442

Error Number: 1146
Table 'db_bagaroung.product_types' doesn't exist
SELECT * FROM (`product_types`)
Filename: D:\OpenServer\domains\bagaround.ru\system\database\DB_driver.php
Line Number: 330

**Comment by cbnuke** [comment]
Exactly it don't work. Because this repo only source code. Don't have database.
And I don't shared database. Cause main thing only shared code with my friend.
